
package com.szeastroc.icebox.newprocess.webservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebSitePortType", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com")
@XmlSeeAlso({
   ObjectFactory.class
})
public interface WebSitePortType {


    /**
     * 
     * @param info
     * @return
     *     returns com.example.demo.webservice.WbSiteResponseVO
     */
    @WebMethod(action = "urn:getWBSites")
    @WebResult(targetNamespace = "http://action.website.webservice.net.crm.neusoft.com")
    @RequestWrapper(localName = "getWBSites", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com", className = "com.example.demo.webservice.GetWBSites")
    @ResponseWrapper(localName = "getWBSitesResponse", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com", className = "com.example.demo.webservice.GetWBSitesResponse")
    public WbSiteResponseVO getWBSites(
        @WebParam(name = "info", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com")
        String info);

    /**
     * 
     * @param args
     */
    @WebMethod(action = "urn:main")
    @Oneway
    @RequestWrapper(localName = "main", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com", className = "com.example.demo.webservice.Main")
    public void main(
        @WebParam(name = "args", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com")
        List<String> args);

    /**
     * 
     * @param request
     * @return
     *     returns com.example.demo.webservice.WbSiteResponseVO
     */
    @WebMethod(action = "urn:getWBMail")
    @WebResult(targetNamespace = "http://action.website.webservice.net.crm.neusoft.com")
    @RequestWrapper(localName = "getWBMail", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com", className = "com.example.demo.webservice.GetWBMail")
    @ResponseWrapper(localName = "getWBMailResponse", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com", className = "com.example.demo.webservice.GetWBMailResponse")
    public WbSiteResponseVO getWBMail(
        @WebParam(name = "request", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com")
        WbSiteRequestVO request);

    /**
     * 
     * @param request
     * @return
     *     returns .WbSiteResponseVO
     */
    @WebMethod(action = "urn:getWBSite")
    @WebResult(targetNamespace = "http://action.website.webservice.net.crm.neusoft.com")
    @RequestWrapper(localName = "getWBSite", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com", className = "com.example.demo.webservice.GetWBSite")
    @ResponseWrapper(localName = "getWBSiteResponse", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com", className = "com.example.demo.webservice.GetWBSiteResponse")
    public WbSiteResponseVO getWBSite(
        @WebParam(name = "request", targetNamespace = "http://action.website.webservice.net.crm.neusoft.com")
        WbSiteRequestVO request);

}
